services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: Geeth@dheepi99
      MYSQL_DATABASE: stockdb
    networks:
      - stocknet
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./UserService
    container_name: UserService
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stockdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Geeth@dheepi99
    networks:
      - stocknet

networks:
  stocknet:
    driver: bridge

volumes:
  mysql_data:
