spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb
    username: root
    password: Geeth@dheepi99
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use "validate" or "none" in prod
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
